### ISSUE TITLE
UOM is not updated in ST message

### ISSUE THREAD

**Issue by NickWaterton** [shbatm/PyISY#13]
I don't know if this is a bug, or a feature request:

What I have found is that some devices (mini remote in my case) send uom in their status updates, but not in their control events

This means that the uom gets set to '0' or `None`, which is then used for status updates (which do include the uom, but this never updates the node).

Example:
```
[D Main                ] ISY Update Received:
<?xml version="1.0"?><Event seqnum="217" sid="uuid:37"><control>FDSTOP</control><action>0</action><node>44 B5 6C 1</node><eventInfo></eventInfo></Event>
[I Main                ] Node 44 B5 6C 1 (DeckRemote - A) received event FDSTOP(fade_stop), value: 0, uom: None(unknown)
[I Main                ] bublishing: /isy_status/DeckRemote - A/dim 0 (UOM:unknown)
[D Main                ] ISY Node Control Event: 44 B5 6C 1 FDSTOP 0
[D Main                ] ISY Update Received:
<?xml version="1.0"?><Event seqnum="218" sid="uuid:37"><control>ST</control><action uom="100" prec="0">150</action><node>44 B5 6C 1</node><eventInfo></eventInfo><fmtAct>59%</fmtAct></Event>
[I Main                ] Node: 44 B5 6C 1 (DeckRemote - A) changed to 150 (150)
[D Main                ] ISY Updated Node: 44 B5 6C 1
[I Main                ] bublishing: /isy_status/DeckRemote - A 150 (UOM:unknown)
```
I am trapping this currently, as I use uom to scale the values to percentages ('100' = byte to percent in my code)

The code that handles this is in `Nodes/__init__.py` line 173:
```
    def _upmsg(self, xmldoc):
        """Update nodes from event stream message."""
        nid = value_from_xml(xmldoc, ATTR_NODE)
        nval = int(value_from_xml(xmldoc, ATTR_ACTION))
        self.get_by_id(nid).status.update(nval, force=True, silent=True)
        self.isy.log.debug("ISY Updated Node: " + nid)
```
as you can see uom and prec are not extracted and used to update the node (unlike control events):
Extract is easy
```
prec = attr_from_xml(xmldoc, ATTR_ACTION, ATTR_PREC, None)
uom = attr_from_xml(xmldoc, ATTR_ACTION, ATTR_UOM, None)
```
but there are no node setters for these values, 
```
nid = value_from_xml(xmldoc, ATTR_NODE)
nval = int(value_from_xml(xmldoc, ATTR_ACTION))
uom = attr_from_xml(xmldoc, ATTR_ACTION, ATTR_UOM, None)
self.get_by_id(nid)._uom = uom
self.get_by_id(nid).status.update(nval, force=True, silent=True)
```
This works (for uom), but is not a real solution.

Thanks.

**Comment by shbatm** [comment]
Interesting. UOM/PREC isn't *supposed* to change from the initial query of each nodes' status from `/rest/nodes`, which is why they are set initally and there are no `ivar` definitions for UOM/PREC, but battery devices provide an invalid status (empty value) until they're first used after rebooting the ISY.

```xml
<property id="ST" value="" formatted=" " uom="0"/>
```

I'll take a look when I get a chance--there is some logic (but I'm not sure if it's in PyISY or Home Assistant code at the moment) to handle unknown statuses for these devices, but I think it omits updating PREC/UOM on the first update.

**Comment by shbatm** [comment]
@NickWaterton -- can you test the most recent update? I haven't pushed it as an update to PyPi yet since it hasn't been fully tested, but you can install it locally by cloning this repo and installing with `pip install -e ./`.

Let me know if you have any issues--once I get a chance to test it on my dev machine I can push the update to PyPi

**Comment by NickWaterton** [comment]
OK, I removed my fix, and pulled the git latest master.

Seems to work. I'll leave it running to see if anything odd turns up.

**Comment by shbatm** [comment]
Great! Let me know if you see anything and I'll run it on my dev box this week to make sure there are no issues.

Just to document the changes: when an update message is received for a node's status, the UOM and PREC are checked and if they changed, they are updated.  There are now manual `setter` functions for PREC and UOM if they need to be overridden for any other reason--they will NOT throw an update event like the actual status though.
